### ISSUE TITLE
Just a Suggestion 

### ISSUE THREAD

**Issue by galaxytwenty** [RafmexHD/SignDye#1]
Wow, Nice Plugin.

can you make That Player with the Permission "signdye.use" can color every single lines Like

-Line1 (Red)  - Red Dye
-Line2 (Blue)  - Blue Dye or Lappis
-Line3 (White)  - White Dye or bonemeal
-Line4 (Green)  -  Green Dye 

Thank you for The Plugin. i think i can use this as well

**Comment by RafmexHD** [comment]
i think so,
but how should he select the line?
i think a form would do best

**Comment by galaxytwenty** [comment]
im thinking **that** would be a **good idea** 
For **Example**

**Sign:**
_line1: example example example
line2: example example example
line3: example RafmexHD example
line4: example example example_

now i run the command **/color RafmexHD**, and when i have a dye in the hand an tap a sign **only** the word ### RafmexHD change there color.

i mean when type **/color example** then **red dye in my hand** and **tapping a sign** only the word **example** change there color in red.

can you make this ?

**Best thx for Answer**

**Comment by RafmexHD** [comment]
ok i will try it :)

**Comment by galaxytwenty** [comment]
ouh, you can try to change all Other Word in Standart color, and the one word in dye color ?.

**Comment by galaxytwenty** [comment]
thanks

**Comment by RafmexHD** [comment]
yes

**Comment by RafmexHD** [comment]
uhmm are you english or american?

**Comment by galaxytwenty** [comment]
I´m German, but when you say, maybe i can help ?

**Comment by RafmexHD** [comment]
yes im too, uhm i tried to express the functionality in the description but it really sucked.
i wanted to say that its able to dye the sign you tapped, that its able to work with landprotection and it also checks permissions for the player
thanks for your help ❤️

**Comment by galaxytwenty** [comment]
Soll ich das für dich machen ?

**Comment by RafmexHD** [comment]
wenn du zeit und lust hast gerne :)

**Comment by galaxytwenty** [comment]
hast du Discord ?

**Comment by RafmexHD** [comment]
ja RafmexGHG#4459

**Comment by RafmexHD** [comment]
Note: continued talking on discord
